version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Navigating to application directory...
      - cd frontend/react-app
      - echo Clean installing dependencies using package-lock.json...
      - npm ci
  build:
    commands:
      - echo Navigating to application directory...
      - echo Building React application...
      - npm run build
  post_build:
    commands:
      - echo Syncing build artifacts to S3...
      - aws s3 sync frontend/react-app/build/ s3://simplylearn-store-431445718171-us-east-2-an --delete
