version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    AWS_ACCOUNT_ID: "431445718171"
    IMAGE_REPO_NAME: "ecommerce/user-service"
    IMAGE_TAG: "user-latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_COMMIT_HASH | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - if [ -n "$CODEBUILD_RESOLVED_COMMIT_HASH" ]; then TAG=$(echo $CODEBUILD_RESOLVED_COMMIT_HASH | cut -c 1-7); else TAG="build-$CODEBUILD_BUILD_NUMBER"; fi
      - echo "export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME" > env_vars
      - echo "export IMAGE_TAG=$TAG" >> env_vars
      - source env_vars
      - echo "Targeting Image Tag: $IMAGE_TAG"
  build:
    commands:
      - source env_vars
      - echo Build started on $(date)
      - echo Building the Docker image...
      - cd services/product-service
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - source env_vars
      - echo Build completed on $(date)
      - echo Pushing the Docker images to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file for ECS / deployment...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
